### ISSUE TITLE
set html string

### ISSUE THREAD

**Issue by siggj** [aryaxt/iOS-Rich-Text-Editor#54]
Hello,
Really nice library ! 
Can we set HTML text like uitextview.htmltext = @"<b>bold</b>" or something like this ?
The goal is to display text in good style when i want to display it in the textview

Thanks in advance !

**Comment by Deadpikle** [comment]
On the List_Implementation branch, there's a setHtmlString: method that you can use. Send it an HTML-formatted NSString and it'll take care of changing it into an NSAttributedString for you.
