### ISSUE TITLE
Convert html text to NSString

### ISSUE THREAD

**Issue by Milan3792** [aryaxt/iOS-Rich-Text-Editor#58]
is there any method that could help me display the text converted from html string?

**Comment by Deadpikle** [comment]
If you have an HTML NSString, you can display it with `setHtmlString:`, which will automatically convert the NSString to an NSAttributedString and display it in the text view. If you already have an NSAttributedString, you can call the `setAttributedText:` method.

**Comment by aryaxt** [comment]
thanks @Deadpikle
